### ISSUE TITLE
issue with collaborator

### ISSUE THREAD

**Issue by workingscorpion** [delivery-much/actions-assigner#7]
today, issue was shown, suddenly.

I tried to change github token or add member to repository collaborator.

Error message

```
Error: Couldn't request review.
  Error: HttpError: Reviews may only be requested from collaborators. One or more of the teams you specified is not a collaborator of the [organization/repository] repository.
```

```
name: auto-reviewer

on:
    pull_request:
        types: [opened, reopened]

jobs:
    assign:
        runs-on: ubuntu-latest
        steps:
            - name: autoReview
              uses: delivery-much/actions-assigner@v1
              with:
                  token: ${{ secretToken }}
                  reviewers:${{ reviewerName }}
```
